### ISSUE TITLE
Stack exception when running `craft` CLI

### ISSUE THREAD

**Issue by mwarkentin** [TopShelfCraft/New-Relic#1]
Hello, it seems that the NR plugin is causing some issues when running the `craft` CLI tool.

```
$ docker exec -it publicsite-web su-exec wave:wave /app/craft install
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getSegment()'

in /app/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /app/vendor/topshelfcraft/new-relic/src/NewRelic.php(59): yii\base\Component->__call('getSegment', Array)
#1 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): topshelfcraft\newrelic\NewRelic->init()
#2 /app/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#3 /app/vendor/craftcms/cms/src/base/Plugin.php(113): yii\base\Module->__construct('new-relic', Object(craft\console\Application), Array)
#4 [internal function]: craft\base\Plugin->__construct('new-relic', Object(craft\console\Application), Array)
#5 /app/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#6 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('topshelfcraft\\n...', Array, Array)
#7 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('topshelfcraft\\n...', Array, Array)
#8 /app/vendor/craftcms/cms/src/services/Plugins.php(788): yii\BaseYii::createObject(Array, Array)
#9 /app/vendor/craftcms/cms/src/services/Plugins.php(199): craft\services\Plugins->createPlugin('new-relic', Array)
#10 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1148): craft\services\Plugins->loadPlugins()
#11 /app/vendor/craftcms/cms/src/console/Application.php(64): craft\console\Application->_postInit()
#12 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#13 /app/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#14 /app/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#15 /app/vendor/craftcms/cms/src/console/Application.php(53): yii\console\Application->__construct(Array)
#16 [internal function]: craft\console\Application->__construct(Array)
#17 /app/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#18 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\console\\A...', Array, Array)
#19 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\console\\A...', Array, Array)
#20 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(252): yii\BaseYii::createObject(Array)
#21 /app/vendor/craftcms/cms/bootstrap/console.php(31): require('/app/vendor/cra...')
#22 /app/craft(21): require('/app/vendor/cra...')
#23 {main}
```

This looks similar to https://github.com/nystudio107/craft-seomatic/issues/39 which was fixed here: https://github.com/nystudio107/craft-seomatic/commit/5253e6b3e0e3f3cff6a42d6a17f51e1ae540d3c4

Any idea if this is something similar?

**Comment by michaelrog** [comment]
Yep, same issue, similar fix. Thanks for catching this, @mwarkentin!

**Comment by mwarkentin** [comment]
Thanks for the (amazingly) fast turnaround on this!
